// All barangays in Surigao City with their actual coordinates and directions
export interface BarangayLocation {
  id: string;
  name: string;
  displayName: string;
  lat: number;
  lng: number;
  address: string;
  direction: string;
  population?: number;
  description?: string;
}

export const SURIGAO_CITY_BARANGAYS: BarangayLocation[] = [
  {
    id: 'brgy-alang-alang',
    name: 'Alang-alang',
    displayName: 'Brgy. Alang-alang',
    lat: 9.7400,
    lng: 125.4200,
    address: 'Alang-alang, Surigao City',
    direction: 'Southwest of city center, agricultural area',
    population: 436,
  },
  {
    id: 'brgy-alegria',
    name: 'Alegria',
    displayName: 'Brgy. Alegria',
    lat: 9.7650,
    lng: 125.4100,
    address: 'Alegria, Surigao City',
    direction: 'West of city center, rural barangay',
    population: 623,
  },
  {
    id: 'brgy-anomar',
    name: 'Anomar',
    displayName: 'Brgy. Anomar',
    lat: 9.7800,
    lng: 125.4000,
    address: 'Anomar, Surigao City',
    direction: 'West barangay, upland area',
    population: 1908,
  },
  {
    id: 'brgy-aurora',
    name: 'Aurora',
    displayName: 'Brgy. Aurora',
    lat: 9.7500,
    lng: 125.4300,
    address: 'Aurora, Surigao City',
    direction: 'Southwest residential area',
    population: 736,
  },
  {
    id: 'brgy-balibayon',
    name: 'Balibayon',
    displayName: 'Brgy. Balibayon',
    lat: 9.8200,
    lng: 125.5200,
    address: 'Balibayon, Surigao City',
    direction: 'Northeast coastal barangay, near bay',
    population: 2216,
  },
  {
    id: 'brgy-baybay',
    name: 'Baybay',
    displayName: 'Brgy. Baybay',
    lat: 9.8400,
    lng: 125.5300,
    address: 'Baybay, Surigao City',
    direction: 'Far north, coastal fishing village',
    population: 311,
  },
  {
    id: 'brgy-bilabid',
    name: 'Bilabid',
    displayName: 'Brgy. Bilabid',
    lat: 9.8500,
    lng: 125.5100,
    address: 'Bilabid, Surigao City',
    direction: 'Far northeast, remote mountain area',
    population: 241,
  },
  {
    id: 'brgy-bitaugan',
    name: 'Bitaugan',
    displayName: 'Brgy. Bitaugan',
    lat: 9.7900,
    lng: 125.4100,
    address: 'Bitaugan, Surigao City',
    direction: 'West-central upland residential',
    population: 707,
  },
  {
    id: 'brgy-bonifacio',
    name: 'Bonifacio',
    displayName: 'Brgy. Bonifacio',
    lat: 9.7500,
    lng: 125.4650,
    address: 'Bonifacio, Surigao City',
    direction: 'Central residential area',
    population: 3822,
  },
  {
    id: 'brgy-buenavista',
    name: 'Buenavista',
    displayName: 'Brgy. Buenavista',
    lat: 9.7350,
    lng: 125.4500,
    address: 'Buenavista, Surigao City',
    direction: 'South-central residential district',
    population: 1168,
  },
  {
    id: 'brgy-cabongbongan',
    name: 'Cabongbongan',
    displayName: 'Brgy. Cabongbongan',
    lat: 9.8050,
    lng: 125.5400,
    address: 'Cabongbongan, Surigao City',
    direction: 'Northeast mountainous area',
    population: 841,
  },
  {
    id: 'brgy-cagniog',
    name: 'Cagniog',
    displayName: 'Brgy. Cagniog',
    lat: 9.8100,
    lng: 125.4800,
    address: 'Cagniog, Surigao City',
    direction: 'North-central suburban area',
    population: 6622,
  },
  {
    id: 'brgy-cagutsan',
    name: 'Cagutsan',
    displayName: 'Brgy. Cagutsan',
    lat: 9.8300,
    lng: 125.4900,
    address: 'Cagutsan, Surigao City',
    direction: 'North residential barangay',
    population: 342,
  },
  {
    id: 'brgy-canlanipa',
    name: 'Canlanipa',
    displayName: 'Brgy. Canlanipa',
    lat: 9.8200,
    lng: 125.4700,
    address: 'Canlanipa, Surigao City',
    direction: 'North-central major residential area',
    population: 11636,
  },
  {
    id: 'brgy-cantiasay',
    name: 'Cantiasay',
    displayName: 'Brgy. Cantiasay',
    lat: 9.7950,
    lng: 125.4450,
    address: 'Cantiasay, Surigao City',
    direction: 'Central-east residential area',
    population: 1047,
  },
  {
    id: 'brgy-capalayan',
    name: 'Capalayan',
    displayName: 'Brgy. Capalayan',
    lat: 9.7700,
    lng: 125.4400,
    address: 'Capalayan, Surigao City',
    direction: 'Central residential district',
    population: 2672,
  },
  {
    id: 'brgy-catadman',
    name: 'Catadman',
    displayName: 'Brgy. Catadman',
    lat: 9.8150,
    lng: 125.5250,
    address: 'Catadman, Surigao City',
    direction: 'Northeast hilly terrain',
    population: 350,
  },
  {
    id: 'brgy-danao',
    name: 'Danao',
    displayName: 'Brgy. Danao',
    lat: 9.7850,
    lng: 125.5150,
    address: 'Danao, Surigao City',
    direction: 'East-central coastal area',
    population: 669,
  },
  {
    id: 'brgy-danawan',
    name: 'Danawan',
    displayName: 'Brgy. Danawan',
    lat: 9.7950,
    lng: 125.5050,
    address: 'Danawan, Surigao City',
    direction: 'East central residential area',
    population: 620,
  },
  {
    id: 'brgy-day-asan',
    name: 'Day-asan',
    displayName: 'Brgy. Day-asan',
    lat: 9.8000,
    lng: 125.4550,
    address: 'Day-asan, Surigao City',
    direction: 'North-central community',
    population: 2032,
  },
  {
    id: 'brgy-ipil',
    name: 'Ipil',
    displayName: 'Brgy. Ipil',
    lat: 9.7600,
    lng: 125.4700,
    address: 'Ipil, Surigao City',
    direction: 'Central commercial-residential district',
    population: 4692,
  },
  {
    id: 'brgy-libuac',
    name: 'Libuac',
    displayName: 'Brgy. Libuac',
    lat: 9.7450,
    lng: 125.4800,
    address: 'Libuac, Surigao City',
    direction: 'South-central barangay',
    population: 997,
  },
  {
    id: 'brgy-lipata',
    name: 'Lipata',
    displayName: 'Brgy. Lipata',
    lat: 9.7550,
    lng: 125.5000,
    address: 'Lipata, Surigao City',
    direction: 'Central-east commercial area',
    population: 2872,
  },
  {
    id: 'brgy-lisondra',
    name: 'Lisondra',
    displayName: 'Brgy. Lisondra',
    lat: 9.7500,
    lng: 125.4900,
    address: 'Lisondra, Surigao City',
    direction: 'Central business district',
    population: 858,
  },
  {
    id: 'brgy-luna',
    name: 'Luna',
    displayName: 'Brgy. Luna',
    lat: 9.7400,
    lng: 125.4600,
    address: 'Luna, Surigao City',
    direction: 'South-central major residential area',
    population: 13233,
  },
  {
    id: 'brgy-mabini',
    name: 'Mabini',
    displayName: 'Brgy. Mabini',
    lat: 9.7650,
    lng: 125.4800,
    address: 'Mabini, Surigao City',
    direction: 'Central residential community',
    population: 2347,
  },
  {
    id: 'brgy-mabua',
    name: 'Mabua',
    displayName: 'Brgy. Mabua',
    lat: 9.7550,
    lng: 125.4300,
    address: 'Mabua, Surigao City',
    direction: 'West-central agricultural area',
    population: 3363,
  },
  {
    id: 'brgy-manyagao',
    name: 'Manyagao',
    displayName: 'Brgy. Manyagao',
    lat: 9.7700,
    lng: 125.4200,
    address: 'Manyagao, Surigao City',
    direction: 'West residential barangay',
    population: 956,
  },
  {
    id: 'brgy-mapawa',
    name: 'Mapawa',
    displayName: 'Brgy. Mapawa',
    lat: 9.7800,
    lng: 125.4300,
    address: 'Mapawa, Surigao City',
    direction: 'West-central upland area',
    population: 1270,
  },
  {
    id: 'brgy-mat-i',
    name: 'Mat-i',
    displayName: 'Brgy. Mat-i',
    lat: 9.7620,
    lng: 125.4380,
    address: 'Mat-i, Surigao City',
    direction: 'Central-west residential area, adjacent to Serna',
    population: 6617,
  },
  {
    id: 'brgy-nabago',
    name: 'Nabago',
    displayName: 'Brgy. Nabago',
    lat: 9.8000,
    lng: 125.4650,
    address: 'Nabago, Surigao City',
    direction: 'North-central community area',
    population: 1167,
  },
  {
    id: 'brgy-nonoc',
    name: 'Nonoc',
    displayName: 'Brgy. Nonoc',
    lat: 9.8250,
    lng: 125.5500,
    address: 'Nonoc, Surigao City',
    direction: 'Far northeast island barangay',
    population: 1107,
  },
  {
    id: 'brgy-orok',
    name: 'Orok',
    displayName: 'Brgy. Orok',
    lat: 9.7300,
    lng: 125.4400,
    address: 'Orok, Surigao City',
    direction: 'South upland barangay',
    population: 1372,
  },
  {
    id: 'brgy-poctoy',
    name: 'Poctoy',
    displayName: 'Brgy. Poctoy',
    lat: 9.7350,
    lng: 125.4700,
    address: 'Poctoy, Surigao City',
    direction: 'South-central residential area',
    population: 1991,
  },
  {
    id: 'brgy-punta-bilar',
    name: 'Punta Bilar',
    displayName: 'Brgy. Punta Bilar',
    lat: 9.7250,
    lng: 125.4500,
    address: 'Punta Bilar, Surigao City',
    direction: 'Southern coastal point',
    population: 1371,
  },
  {
    id: 'brgy-quezon',
    name: 'Quezon',
    displayName: 'Brgy. Quezon',
    lat: 9.7400,
    lng: 125.4500,
    address: 'Quezon, Surigao City',
    direction: 'South-central residential district',
    population: 2339,
  },
  {
    id: 'brgy-rizal',
    name: 'Rizal',
    displayName: 'Brgy. Rizal',
    lat: 9.7650,
    lng: 125.4550,
    address: 'Rizal, Surigao City',
    direction: 'Central residential area',
    population: 7492,
  },
  {
    id: 'brgy-sabang',
    name: 'Sabang',
    displayName: 'Brgy. Sabang',
    lat: 9.7800,
    lng: 125.4550,
    address: 'Sabang, Surigao City',
    direction: 'Central-east major residential area',
    population: 6114,
  },
  {
    id: 'brgy-san-isidro',
    name: 'San Isidro',
    displayName: 'Brgy. San Isidro',
    lat: 9.7500,
    lng: 125.4750,
    address: 'San Isidro, Surigao City',
    direction: 'Central residential community',
    population: 629,
  },
  {
    id: 'brgy-san-jose',
    name: 'San Jose',
    displayName: 'Brgy. San Jose',
    lat: 9.7700,
    lng: 125.4900,
    address: 'San Jose, Surigao City',
    direction: 'Central-east residential area',
    population: 1356,
  },
  {
    id: 'brgy-san-juan',
    name: 'San Juan',
    displayName: 'Brgy. San Juan',
    lat: 9.7750,
    lng: 125.4700,
    address: 'San Juan, Surigao City',
    direction: 'Central major residential district',
    population: 16565,
  },
  {
    id: 'brgy-san-pedro',
    name: 'San Pedro',
    displayName: 'Brgy. San Pedro',
    lat: 9.7850,
    lng: 125.4750,
    address: 'San Pedro, Surigao City',
    direction: 'Central-east residential area',
    population: 919,
  },
  {
    id: 'brgy-san-roque',
    name: 'San Roque',
    displayName: 'Brgy. San Roque',
    lat: 9.7720,
    lng: 125.4880,
    address: 'San Roque, Surigao City',
    direction: 'Central market district',
    population: 1596,
  },
  {
    id: 'brgy-serna',
    name: 'Serna',
    displayName: 'Brgy. Serna',
    lat: 9.7600,
    lng: 125.4400,
    address: 'Serna, Surigao City',
    direction: 'Central-west residential barangay',
    population: 1701,
  },
  {
    id: 'brgy-sidlakan',
    name: 'Sidlakan',
    displayName: 'Brgy. Sidlakan',
    lat: 9.7950,
    lng: 125.5200,
    address: 'Sidlakan, Surigao City',
    direction: 'East-north remote barangay',
    population: 331,
  },
  {
    id: 'brgy-silop',
    name: 'Silop',
    displayName: 'Brgy. Silop',
    lat: 9.7850,
    lng: 125.4900,
    address: 'Silop, Surigao City',
    direction: 'Central-east residential area',
    population: 1602,
  },
  {
    id: 'brgy-sugbay',
    name: 'Sugbay',
    displayName: 'Brgy. Sugbay',
    lat: 9.7500,
    lng: 125.4350,
    address: 'Sugbay, Surigao City',
    direction: 'South-west barangay',
    population: 554,
  },
  {
    id: 'brgy-sukailang',
    name: 'Sukailang',
    displayName: 'Brgy. Sukailang',
    lat: 9.7650,
    lng: 125.4250,
    address: 'Sukailang, Surigao City',
    direction: 'West-central agricultural area',
    population: 1396,
  },
  {
    id: 'brgy-taft',
    name: 'Taft',
    displayName: 'Brgy. Taft',
    lat: 9.7700,
    lng: 125.4750,
    address: 'Taft, Surigao City',
    direction: 'Central major commercial-residential hub',
    population: 19242,
  },
  {
    id: 'brgy-talisay',
    name: 'Talisay',
    displayName: 'Brgy. Talisay',
    lat: 9.7300,
    lng: 125.4700,
    address: 'Talisay, Surigao City',
    direction: 'South residential barangay',
    population: 1166,
  },
  {
    id: 'brgy-togbongon',
    name: 'Togbongon',
    displayName: 'Brgy. Togbongon',
    lat: 9.8150,
    lng: 125.4600,
    address: 'Togbongon, Surigao City',
    direction: 'North-central residential district',
    population: 2257,
  },
  {
    id: 'brgy-trinidad',
    name: 'Trinidad',
    displayName: 'Brgy. Trinidad',
    lat: 9.7550,
    lng: 125.4550,
    address: 'Trinidad, Surigao City',
    direction: 'Central residential community',
    population: 2726,
  },
  {
    id: 'brgy-washington',
    name: 'Washington',
    displayName: 'Brgy. Washington',
    lat: 9.7800,
    lng: 125.4850,
    address: 'Washington, Surigao City',
    direction: 'Central-east major residential hub',
    population: 19319,
  },
  {
    id: 'brgy-zaragoza',
    name: 'Zaragoza',
    displayName: 'Brgy. Zaragoza',
    lat: 9.8000,
    lng: 125.4400,
    address: 'Zaragoza, Surigao City',
    direction: 'North-west residential barangay',
    population: 1200,
  },
];

export const getBarangayById = (barangayId: string): BarangayLocation | undefined => {
  return SURIGAO_CITY_BARANGAYS.find(b => b.id === barangayId);
};

export const getBarangayOptions = () => {
  return SURIGAO_CITY_BARANGAYS.map(b => ({
    value: b.id,
    label: `${b.displayName} (Pop: ${b.population?.toLocaleString()})`,
  }));
};

